name: cd-auditservice
'on':
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
      run_number:
        description: Build Number
        required: true
  workflow_run:
    workflows:
      - ci-auditservice
    branches:
      - main
    paths:
      - '**/auditservice/**'
    types:
      - completed
env:
  REPOSITORY_NAME: adapter-test
jobs:
  set-environment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - if: |
          github.event.inputs.environment == '' && contains(github.event.workflow_run.head_branch, 'main')
        name: Set main env
        run: |-
          echo ENVIRONMENT=main>> $GITHUB_ENV
          echo "RUN_NUMBER=${{github.event.workflow_run.run_number}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
      - if: |
          github.event.inputs.environment == 'main'
        run: |
          echo ENVIRONMENT=main>> $GITHUB_ENV
          echo "RUN_NUMBER=${{github.event.inputs.run_number}}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: set Env
        id: setEnv
        run: |
          export ENVIRONMENT="${{ env.ENVIRONMENT }}"
          export RUN_NUMBER="${{ env.RUN_NUMBER }}"          
          export BRANCH_NAME="${{ env.BRANCH_NAME }}"          
          echo "::set-output name=environment::${ENVIRONMENT}"
          echo "::set-output name=run_number::${RUN_NUMBER}"
          echo "::set-output name=branch_name::${BRANCH_NAME}"
    outputs:
      environment: ${{ steps.setEnv.outputs.environment }}
      run_number: ${{ steps.setEnv.outputs.run_number }}
      branch_name: ${{ steps.setEnv.outputs.branch_name }}
  main:
    runs-on: ubuntu-latest
    needs: set-environment
    if: (needs.set-environment.outputs.environment == 'main' && github.event.workflow_run.conclusion != 'failure')
    environment: main
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: C8H4wZg
          publish-profile: ${{ secrets.AZURE_C8H4WZG_PUBLISH_PROFILE }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.REPOSITORY }}:${{needs.set-environment.outputs.run_number}}
